name: Pull Requests Check

on:
  pull_request:

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          run_install: true
          version: 

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: lts
          cache: pnpm

      - name: Install Deps
        run: pnpm install

      - name: Build docs
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: pnpm run build
